version: '3.8'

services:
  app:
    build: .
    container_name: gmail_sheets_automation
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount the current directory to allow live reloading and access to json keys
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload